### ISSUE TITLE
Add hover support to menu in desktop mode

### ISSUE THREAD

**Issue by valadas** [eraware/Eraware.MinimalSkin#326]
Add hover support to menu in desktop mode

**Comment by jeremy-farrance** [comment]
Recommended reading from a friend. :)
https://css-tricks.com/in-praise-of-the-unambiguous-click-menu/

**Comment by valadas** [comment]
I agree with most of that, but to support a wide use case, I want the base template to support having the parent page be a real page and not only contain it's sub-pages as well as many clients expecting hover behavior. It will be implemented in a fashion that is complementary and does not hinder mobile and keyboard support. I logged it here as I just released v1.0.0 (which had a goal of being totally bootstrap independent making it officially optional). I need to work some more on details of that menu though like hover and aria-attributes and even better keyboard support.
