### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by leedavi** [eraware/Eraware.MinimalSkin#50]
I've built the install package with yarn and then tried to install the skin package into DNN9.4.1

I get this error..

StartJob Reading files
Info File skinResources.zip read successfully
Info File containersResources.zip read successfully
Info File manifest.dnn read successfully
Info File releaseNotes.txt read successfully
Info File LICENSE read successfully
EndJob Reading files done.
StartJob Reading Installation Manifest file
**Failure Unrecognizable Package manifest**

I remove the manifesto file from the install package and this skin uploads, I unzip the resources zip onto the server and the skin works.

I've attached the manifesto file that was generated and in the package.

[manifest.zip](https://github.com/eraware/Eraware.MinimalSkin/files/3851692/manifest.zip)

**Comment by valadas** [comment]
Hi @leedavi 

This was caused by the dnn manifest not supporting comments and should have been resolved by #48 

Did you build from the development branch, i have not yet merged that one into master and publish a new release...

**Comment by valadas** [comment]
Also, just FYI this is still a bit of work in progress and some options still are just questions that do not affect the build, for instance selecting to not include bootstrap is currently not yet supported, I am trying to finish that next week or some such :)

**Comment by leedavi** [comment]
OK, thx.  I'll give it another try and let you know how it goes.

**Comment by valadas** [comment]
Cool, ping me up if you still have issues...

**Comment by leedavi** [comment]
OK, works great with the development branch.
