### ISSUE TITLE
FastAddModule

### ISSUE THREAD

**Issue by leedavi** [eraware/Eraware.MinimalSkin#52]
I think a great enhancement would be to include Sachas' FastAddModule

https://github.com/sachatrauwaen/OpenContent-Templates/tree/master/Dnn9FastAddModule

I've done a quick addition to you skin on my install, but you might want to have a look a this:

<% if (DotNetNuke.Security.PortalSecurity.IsInRoles("Administrators")) { %>

<dnn:DnnCssInclude runat="server" FilePath="Dnn9FastAddModule/template.css" PathNameAlias="SkinPath" />
<dnn:DnnJsInclude runat="server" FilePath="Dnn9FastAddModule/template.js" PathNameAlias="SkinPath" />

<% } %>

It's a great improvement to DNN and I believe it should be put into the core.  I've talked to Sacha on if he's OK with it in the core, and he is happy to allow that.  I'm trying to find the time to work out how to get it in the core so the code link is automatically added to the skin, by DNN.  But I haven't found the time yet.

**Comment by valadas** [comment]
I also believe such a thing should be on the core, I gonna leave the issue here though, I might give a try and maybe later sumit a PR to Dnn instead.

**Comment by leedavi** [comment]
OK, great.  I've been trying to find the time to look into this, but have not managed to do anything.

But when seeing this project I thought:  It is designed to be on the skin, and maybe that would be the best place for it and would need no changes to DNN core, just delivered with the core and skin designers can choose to use it or not.  This project could serve as an educational example of usage.

**Comment by leedavi** [comment]
One irritation is the HTML module "ALWAYS" a favorite.  I don't know who decided that, but it seems wrong to me.  Maybe if this is on the skin, the change required in the DNN core should be to allow the HTML module to be removed from favorites.

**Comment by valadas** [comment]
There is a place in the database to set the default module (preferred), there is just no UI for it...

**Comment by leedavi** [comment]
Ah!!  thx I'll look at that.

**Comment by valadas** [comment]
I will close this issue here, there are some plans in the Platform soon to improve that at the core level.
